name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build test image
        run: docker build -t final-backend ./backend

      - name: Run test container
        run: docker run -d --name test-backend -p 8000:8000 final-backend

      - name: Health check
        run: |
          sleep 3
          curl -f http://localhost:8000/yanlis

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t final-backend ./backend